name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Data Types : Null'
      id: data-types-null
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Data Types : Null'
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DATA-TYPES-NULL_RESULTS: "${{steps.data-types-null.outputs.result}}"
      with:
        runners: data-types-null
